{{ if eq (include "dynatrace-operator.needAutopilotAllowlisting" .) "true" }}
apiVersion: auto.gke.io/v1
kind: AllowlistSynchronizer
metadata:
  name: hook-demo
  annotations:
    "helm.sh/hook": pre-install, post-delete, pre-upgrade, pre-rollback
spec:
  allowlistPaths:
  - Dynatrace/csidriver/1.7.0/*
  - Dynatrace/logmonitoring/1.7.0/*
  - Dynatrace/csijob/1.7.0/* 
{{- end -}}
